services:

  postgres:
    build:
      context: ./rest-api
      dockerfile: dockerfile-db
    networks:
      - project_net
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=MyERPCompanion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

  rest-api:
    build:
      context: ./rest-api
      dockerfile: dockerfile-api
    networks:
      - project_net
    ports:
      - "8000:8000"
    volumes:
      - ./rest-api/rest_api/:/rest_api
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:changeme@postgres/MyERPCompanion
      - SECRET_KEY=secret
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=admin123
      - ADMINS_GROUP_KEY=admins
      - ADMINS_GROUP_DESC=Admins
    depends_on:
      - postgres
    command:
      sh -c "uvicorn main:start_app --host 0.0.0.0 --port 8000 --reload"

  redis:
    build:
      context: ./desktop-app
      dockerfile: dockerfile-redis
    networks:
      - project_net
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: [
      "redis-server",
      "--requirepass", "changeme",
      "--save", "60", "1",
      "--appendonly", "no",
      "--dir", "/data"
    ]

  desktop-app:
    build:
      context: ./desktop-app
      dockerfile: dockerfile-desktop
    networks:
      - project_net
    volumes:
      - ./desktop-app/desktop_app/:/desktop_app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - API_URL=http://rest-api:8000/api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=changeme
    depends_on:
      - redis
    stdin_open: true
    tty: true
    command:
      sh -c "python main.py"

volumes:
  postgres-data:
  redis-data:

networks:
  project_net:
    driver: bridge