services:

  postgres:
    build:
      context: ./rest-api
      dockerfile: dockerfile-db
    networks:
      - project_net
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=MyERPCompanion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

  rest-api:
    build:
      context: ./rest-api
      dockerfile: dockerfile-api
    networks:
      - project_net
    ports:
      - "8000:8000"
    volumes:
      - ./rest-api/rest_api/:/rest_api
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:changeme@postgres/MyERPCompanion
      - SECRET_KEY=secret
      - SUPERUSER_USERNAME=admin
      - SUPERUSER_PASSWORD=admin
    depends_on:
      - postgres
    command:
      sh -c "python -c 'import sys; path=\"/rest_api\"; sys.path.append(path) if path not in sys.path else None' &&
      uvicorn main:start_app --host 0.0.0.0 --port 8000 --reload"

#  web-app:
#    build:
#      context: ./web-app
#      dockerfile: dockerfile-web
#    networks:
#      - project_net
#    ports:
#      - "9000:9000"
#    volumes:
#      - ./web-app/web_app/:/web_app
#    command:
#      sh -c "python manage.py wait_for_redis &&
#      python manage.py wait_for_api &&
#      python manage.py runserver 0.0.0.0:9000"
#    depends_on:
#      - redis
#      - rest-api

#  redis:
#    build:
#      context: ./web-app
#      dockerfile: dockerfile-cache
#    networks:
#      - project_net
#    ports:
#      - "6379:6379"

volumes:
  postgres-data:

networks:
  project_net:
    driver: bridge