FROM python:3.12-bookworm
LABEL maintainer="Patryk Kerlin"

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /tmp/requirements.txt
COPY ./rest_api /rest_api
WORKDIR /rest_api
EXPOSE 8000

RUN python -m venv /pyenv
RUN /pyenv/bin/pip install --upgrade pip
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y postgresql-client --no-install-recommends
RUN rm -rf /var/lib/apt/lists/*
RUN /pyenv/bin/pip install -r /tmp/requirements.txt
RUN rm -rf /tmp

RUN useradd -m -d /rest_api -s /bin/bash rest-api

RUN mkdir -p /rest_api
RUN chown -R rest-api:rest-api /rest_api
RUN chmod -R 755 /rest_api

ENV PATH="/pyenv/bin:$PATH"

USER rest-api