FROM python:3.14-trixie
LABEL maintainer="Patryk Kerlin"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/project \
    PATH="/project/bin:$PATH" \
    PYTHONPATH="/rest_api"

RUN apt-get update && \
    apt-get install -y \
    postgresql-client --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY /rest_api/requirements.txt /tmp/requirements.txt

RUN python -m venv $VIRTUAL_ENV && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

WORKDIR /rest_api

RUN useradd -m -d /rest_api -s /bin/bash rest-api && \
    mkdir -p /media && \
    touch /media/.keep && \
    chown -R rest-api:rest-api /rest_api /media && \
    chmod -R 775 /rest_api /media

USER rest-api

EXPOSE 8000
