class AppDimensions:
    RADIUS_SM = 6
    RADIUS_MD = 8

    SPACE_2XS = 4
    SPACE_XS = 6
    SPACE_SM = 8
    SPACE_MD = 10
    SPACE_LG = 12
    SPACE_XL = 16
    SPACE_2XL = 24

    CONTROL_HEIGHT = 44
    ICON_BUTTON_WIDTH = 48
    CART_BUTTON_ICON_SIZE = 24

    PADDING_INPUT_HORIZONTAL = 12
    PADDING_INPUT_VERTICAL = 8
    PADDING_FORM_HORIZONTAL = 18
    PADDING_FORM_VERTICAL = 16
    PADDING_BUTTON_HORIZONTAL = 22
    PADDING_BUTTON_VERTICAL = 10
    PADDING_BUTTON_HORIZONTAL_COMPACT = 16
    PADDING_BUTTON_VERTICAL_COMPACT = 8

    CONTENT_WIDTH_RATIO = 0.75
    CONTENT_HEIGHT_RATIO = 0.75
    AUTH_FORM_WIDTH = 340
    AUTH_CARD_WIDTH = 480
    AUTH_OVERLAY_PADDING_HORIZONTAL = 40
    AUTH_OVERLAY_PADDING_VERTICAL = 30
    AUTH_CARD_PADDING_HORIZONTAL = 40
    AUTH_CARD_PADDING_VERTICAL = 30
    DIALOG_IMAGE_SIZE = 800
    DIALOG_THUMB_SIZE = 96

    STATUS_LOADING_RING_SIZE = 20
    ORDER_PAYMENT_ICON_SLOT_WIDTH = 28
    ORDER_PAYMENT_ICON_SLOT_HEIGHT = 40

    ORDER_ITEMS_INDEX_COL_WIDTH = 110
    ORDER_ITEMS_EAN_COL_WIDTH = 130
    ORDER_ITEMS_QUANTITY_COL_WIDTH = 90
    ORDER_ITEMS_GAP_COL_WIDTH = 20
    ORDER_ITEMS_DISCOUNTS_COL_WIDTH = 220
    ORDER_META_LABEL_COL_WIDTH = 220

    CREATE_ORDER_IMAGE_BOX_SIZE = 64
    CREATE_ORDER_IMAGE_SIZE = 56
