from enum import StrEnum, IntEnum


class ViewMode(StrEnum):
    NONE = "none"
    SEARCH = "search"
    CREATE = "create"
    READ = "read"
    EDIT = "edit"
    LIST = "list"
    STATIC = "static"


class Module(IntEnum):
    CORE = 1


class ApiActionError(StrEnum):
    FETCH = "data_fetch_fail"
    SAVE = "record_save_fail"
    DELETE = "record_delete_fail"
    GENERIC = "operation_failed"
    IMAGE_UPLOAD = "cant_upload_file"
    IMAGE_UPDATE = "cant_update_image"
    IMAGE_DELETE = "cant_delete_image"
    INVALID_CREDENTIALS = "invalid_credentials"


class View(StrEnum):
    SIDE_MENU = "side_menu"
    CURRENT_USER = "current_user"
    DEPARTMENTS = "departments"
    POSITIONS = "positions"
    EMPLOYEES = "employees"
    WAREHOUSES = "warehouses"
    BINS = "bins"
    CARRIERS = "carriers"
    DELIVERY_METHODS = "delivery_methods"
    UNITS = "units"
    ITEMS = "items"
    BIN_TRANSFER = "bin_transfer"
    SUPPLIERS = "suppliers"
    CATEGORIES = "categories"
    DISCOUNTS = "discounts"
    CURRENCIES = "currencies"
    CUSTOMERS = "customers"
    EXCHANGE_RATES = "exchange_rates"
    PAYMENT_METHODS = "payment_methods"
    SALES_ORDERS = "sales_orders"
    PURCHASE_ORDERS = "purchase_orders"


class EditDisabledView(StrEnum):
    PURCHASE_ORDERS = View.PURCHASE_ORDERS


class Endpoint(StrEnum):
    HEALTH_CHECK = "health-check"
    TRANSLATIONS_BY_LANGUAGE = "translations/by-language"
    TOKEN = "auth/token"
    REFRESH = "auth/refresh"
    CURRENT_USER = "current-user"
    MODULES = "modules"
    USERS = "users"
    DEPARTMENTS = "departments"
    POSITIONS = "positions"
    CURRENCIES = "currencies"
    EMPLOYEES = "employees"
    WAREHOUSES = "warehouses"
    BINS = "bins"
    BINS_GET_BULK = "bins/get-bulk"
    CARRIERS = "carriers"
    DELIVERY_METHODS = "delivery-methods"
    UNITS = "units"
    ITEMS = "items"
    ITEMS_GET_BULK = "items/get-bulk"
    BIN_ITEMS = "bin-items"
    BIN_ITEMS_GET_BULK = "bin-items/get-bulk"
    BIN_ITEMS_CREATE_BULK = "bin-items/create-bulk"
    BIN_ITEMS_UPDATE_BULK = "bin-items/update-bulk"
    BIN_ITEMS_DELETE_BULK = "bin-items/delete-bulk"
    SUPPLIERS = "suppliers"
    CATEGORIES = "categories"
    IMAGES = "images"
    IMAGES_UPDATE_BULK = "images/update-bulk"
    DISCOUNTS = "discounts"
    DISCOUNTS_GET_BULK = "discounts/get-bulk"
    CUSTOMERS = "customers"
    CATEGORY_DISCOUNTS = "category-discounts"
    CATEGORY_DISCOUNTS_GET_BULK = "category-discounts/get-bulk"
    CATEGORY_DISCOUNTS_CREATE_BULK = "category-discounts/create-bulk"
    CATEGORY_DISCOUNTS_UPDATE_BULK = "category-discounts/update-bulk"
    CATEGORY_DISCOUNTS_DELETE_BULK = "category-discounts/delete-bulk"
    CUSTOMER_DISCOUNTS = "customer-discounts"
    CUSTOMER_DISCOUNTS_GET_BULK = "customer-discounts/get-bulk"
    CUSTOMER_DISCOUNTS_CREATE_BULK = "customer-discounts/create-bulk"
    CUSTOMER_DISCOUNTS_UPDATE_BULK = "customer-discounts/update-bulk"
    CUSTOMER_DISCOUNTS_DELETE_BULK = "customer-discounts/delete-bulk"
    ITEM_DISCOUNTS = "item-discounts"
    ITEM_DISCOUNTS_GET_BULK = "item-discounts/get-bulk"
    ITEM_DISCOUNTS_CREATE_BULK = "item-discounts/create-bulk"
    ITEM_DISCOUNTS_UPDATE_BULK = "item-discounts/update-bulk"
    ITEM_DISCOUNTS_DELETE_BULK = "item-discounts/delete-bulk"
    EXCHANGE_RATES = "exchange-rates"
    PAYMENT_METHODS = "payment-methods"
    ORDERS = "orders"
    PURCHASE_ORDERS = "orders/purchase"
    ORDER_ITEMS = "order-items"
    ORDER_ITEMS_GET_BULK = "order-items/get-bulk"
    ORDER_ITEMS_CREATE_BULK = "order-items/create-bulk"
    ORDER_ITEMS_UPDATE_BULK = "order-items/update-bulk"
    ORDER_ITEMS_DELETE_BULK = "order-items/delete-bulk"
    ORDER_STATUSES = "order-statuses"
    ORDER_STATUSES_GET_BULK = "order-statuses/get-bulk"
    ORDER_STATUSES_CREATE_BULK = "order-statuses/create-bulk"
    ORDER_STATUSES_UPDATE_BULK = "order-statuses/update-bulk"
    ORDER_STATUSES_DELETE_BULK = "order-statuses/delete-bulk"
