class AppDimensions:
    MOBILE_WIDTH = 360
    MOBILE_HEIGHT = 800

    SPACE_2XS = 2
    SPACE_XS = 4
    SPACE_SM = 6
    SPACE_MD = 8
    SPACE_LG = 10
    SPACE_XL = 12
    SPACE_2XL = 14
    SPACE_3XL = 16
    SPACE_4XL = 20
    SPACE_5XL = 25

    DIVIDER_HEIGHT = 1

    HEADER_TITLE_SIZE = 20
    HEADER_SUBTITLE_SIZE = 14
    HEADER_TOP_BAR_TITLE_SIZE = 18
    SUMMARY_TITLE_SIZE = 16
    PENDING_TITLE_SIZE = 15

    BACK_BUTTON_WIDTH = 220
    ACTION_BUTTON_WIDTH = 140
    ICON_BUTTON_WIDTH = 48
    INPUT_DENSE_SPACING = 0

    BASE_HIDDEN_FIELD_COL = 1

    AUTH_FORM_WIDTH = 320
    AUTH_CARD_WIDTH = 344

    SUMMARY_WIDTH = 320
    CARD_BORDER_RADIUS = 10

    GALLERY_THUMB_SIZE = 88
    GALLERY_WINDOW_SIZE = 3
    GALLERY_DIALOG_IMAGE_WIDTH = 320
    GALLERY_DIALOG_IMAGE_HEIGHT = 420

    DETAILS_LABEL_COLUMN_WIDTH = 140
    PICK_DETAILS_LABEL_COLUMN_WIDTH = 150
