FROM python:3.14-trixie
LABEL maintainer="Patryk Kerlin"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/project \
    PATH="/project/bin:$PATH" \
    PYTHONPATH="/mobile_app"

COPY /mobile_app/requirements.txt /tmp/requirements.txt

RUN python -m venv $VIRTUAL_ENV && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

WORKDIR /mobile_app

RUN useradd -m -d /mobile_app -s /bin/bash mobile-app && \
    chown -R mobile-app:mobile-app /mobile_app && \
    chmod -R 755 /mobile_app

USER mobile-app
