FROM python:3.14-trixie
LABEL maintainer="Patryk Kerlin"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/project \
    PATH="/project/bin:$PATH" \
    PYTHONPATH="/mobile_app" \
    NVM_DIR=/root/.nvm


RUN apt-get update && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    . "$NVM_DIR/nvm.sh" && nvm install 23 && \
    . "$NVM_DIR/nvm.sh" && nvm alias default 23 && \
    ln -s "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/node" /usr/bin/node && \
    ln -s "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/npm" /usr/bin/npm && \
    ln -s "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/npx" /usr/bin/npx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY /mobile_app/requirements.txt /tmp/requirements.txt
RUN python -m venv $VIRTUAL_ENV && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

WORKDIR /mobile_app

RUN useradd -m -d /mobile_app -s /bin/bash mobile-app && \
    chown -R mobile-app:mobile-app /mobile_app && \
    chmod -R 755 /mobile_app

USER mobile-app
