FROM debian:13
LABEL maintainer="Patryk Kerlin"

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/project \
    PYENV_ROOT=/opt/pyenv \
    PYTHONPATH="/ai_app:/ai_app/models" \
    PATH="/project/bin:/opt/pyenv/bin:/opt/pyenv/shims:$PATH" \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates curl git \
    build-essential make \
    libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
    libffi-dev liblzma-dev tk-dev xz-utils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN rm -rf "$PYENV_ROOT" && \
    git clone "https://github.com/pyenv/pyenv.git" "$PYENV_ROOT" && \
    LATEST_PYTHON_314=$("$PYENV_ROOT/bin/pyenv" install --list | \
        sed "s/^[[:space:]]*//" | \
        grep "^3\.14\." | \
        sort -V | \
        tail -n 1) && \
    echo "Installing Python $LATEST_PYTHON_314" && \
    "$PYENV_ROOT/bin/pyenv" install "$LATEST_PYTHON_314" && \
    "$PYENV_ROOT/bin/pyenv" global "$LATEST_PYTHON_314" && \
    python -m venv "$VIRTUAL_ENV" && \
    python -m pip install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN python -m pip install -r /tmp/requirements.txt && rm -rf /tmp/requirements.txt

WORKDIR /ai_app

RUN useradd -m -d /ai_app -s /bin/bash ai-app && \
    chown -R ai-app:ai-app /ai_app && \
    chmod -R 755 /ai_app && \
    chmod -R a+rX /opt/pyenv

USER ai-app
