FROM python:3.14-trixie
LABEL maintainer="Patryk Kerlin"

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/project \
    PATH="/project/bin:$PATH" \
    PYTHONPATH="/ai_app" \
    NVM_DIR=/root/.nvm \
    PRISMA_NODEENV_EXTRA_ARGS="--node=system"

RUN apt-get update && \
    apt-get install -y curl postgresql-client --no-install-recommends && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && \
    . "$NVM_DIR/nvm.sh" && nvm install 24 && \
    . "$NVM_DIR/nvm.sh" && nvm alias default 24 && \
    ln -s "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/node" /usr/bin/node && \
    ln -s "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/npm" /usr/bin/npm && \
    ln -s "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/npx" /usr/bin/npx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY /ai_app/requirements.txt /tmp/requirements.txt
RUN python -m venv $VIRTUAL_ENV && \
    pip install --upgrade pip && \
    pip install -r /tmp/requirements.txt && \
    rm -rf /tmp/requirements.txt

WORKDIR /ai_app

RUN useradd -m -d /ai_app -s /bin/bash ai-app && \
    mkdir -p /media && \
    touch /media/.keep && \
    chown -R ai-app:ai-app /ai_app /media && \
    chmod -R 775 /ai_app /media

USER ai-app
