FROM redis:7.4-bookworm
LABEL maintainer="Patryk Kerlin"

RUN apt-get update
RUN apt-get upgrade -y
RUN rm -rf /var/lib/apt/lists/*

EXPOSE 6379

CMD ["redis-server", "--save", "", "--appendonly", "no"]