class AppDimensions:
    DESKTOP_WINDOW_WIDTH = 1600
    DESKTOP_WINDOW_HEIGHT = 900
    DESKTOP_WINDOW_MIN_WIDTH = 1024
    DESKTOP_WINDOW_MIN_HEIGHT = 768

    ICON_BUTTON_WIDTH = 48
    SHORTCUT_FONT_SIZE = 10

    COMPACT_SPACING = 6
    TIGHT_SPACING = 4
    FIELD_ROW_SPACING = 8
    BASE_SPACING = 25
    SMALL_SPACING = 10
    MEDIUM_SPACING = 12

    BULK_TRANSFER_HEIGHT = 260
    SECTION_HEIGHT = 250
    SUBSECTION_HEIGHT = 200
    COMPACT_SECTION_HEIGHT = 180
    SMALL_ROW_HEIGHT = 15
    BULK_TRANSFER_BORDER_RADIUS = 6
    BULK_TRANSFER_PADDING = 6
    REPORT_DIALOG_WIDTH_RATIO = 0.98
    REPORT_DIALOG_HEIGHT_RATIO = 0.9

    ANIMATION_DURATION_MS = 300


class ItemViewDimensions:
    GALLERY_HEIGHT = 140
    PRIMARY_BORDER = 4
