class AppDimensions:
    # Window
    DESKTOP_WINDOW_WIDTH = 1600
    DESKTOP_WINDOW_HEIGHT = 900
    DESKTOP_WINDOW_MIN_WIDTH = 1024
    DESKTOP_WINDOW_MIN_HEIGHT = 768

    # Universal scale: radius
    RADIUS_SM = 6
    RADIUS_MD = 8

    # Universal scale: spacing
    SPACE_2XS = 4
    SPACE_XS = 6
    SPACE_SM = 8
    SPACE_MD = 10
    SPACE_LG = 12
    SPACE_XL = 16
    SPACE_2XL = 25

    # Universal scale: control heights
    CONTROL_HEIGHT = 44
    SECTION_HEIGHT_COMPACT = CONTROL_HEIGHT * 4
    SECTION_HEIGHT_REGULAR = 200
    SECTION_HEIGHT_LARGE = 250
    BULK_TRANSFER_HEIGHT_LARGE = 260

    # Universal scale: paddings
    PADDING_INPUT_HORIZONTAL = 12
    PADDING_INPUT_VERTICAL = 8
    PADDING_FORM_HORIZONTAL = 18
    PADDING_FORM_VERTICAL = 16
    PADDING_BUTTON_HORIZONTAL = 22
    PADDING_BUTTON_VERTICAL = 10
    PADDING_BUTTON_HORIZONTAL_COMPACT = 16
    PADDING_BUTTON_VERTICAL_COMPACT = 8

    # Shared values
    ICON_BUTTON_WIDTH = 48
    TOOLBAR_USER_ICON_SIZE = 20
    SHORTCUT_FONT_SIZE = 10
    BUTTON_ROW_SPACING = SPACE_MD
    TABS_BAR_EDGE_PADDING = SPACE_2XL
    TAB_CARD_BORDER_WIDTH = 1
    SIDE_MENU_MIN_WIDTH = 200
    SIDE_MENU_MAX_WIDTH = 320
    SIDE_MENU_CHAR_WIDTH = 9
    SIDE_MENU_EXTRA_WIDTH = 40

    REPORT_DIALOG_WIDTH_RATIO = 0.98
    REPORT_DIALOG_HEIGHT_RATIO = 0.9

    ANIMATION_DURATION_MS = 333
    SMALL_ROW_HEIGHT = 15


class ItemViewDimensions:
    GALLERY_HEIGHT = 140
    PRIMARY_BORDER = 4
