FROM debian:13
LABEL maintainer="Patryk Kerlin"

ENV DEBIAN_FRONTEND=noninteractive \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    VIRTUAL_ENV=/project \
    PYTHONPATH="/desktop_app" \
    NVM_DIR=/opt/nvm \
    PYENV_ROOT=/opt/pyenv \
    PATH="/project/bin:/opt/pyenv/bin:/opt/pyenv/shims:$PATH" \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    NO_AT_BRIDGE=1 \
    XCURSOR_THEME=Adwaita

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates curl git \
    build-essential make \
    libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
    libffi-dev liblzma-dev tk-dev xz-utils \
    x11-apps \
    libx11-dev libgl1 libegl1 libgles2 libxkbcommon0 libxcb1 libxcb-cursor0 libxcb-util1 \
    libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-render0 libxcb-shape0 libxcb-shm0 \
    libxcb-sync1 libxcb-xfixes0 libxcb-xinerama0 libxcb-xkb1 libxcomposite1 libxcursor1 \
    libxdamage1 libxfixes3 libxi6 libxtst6 libnss3 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 \
    libgstreamer1.0-0 libgstreamer-plugins-base1.0-0 gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good gstreamer1.0-libav \
    qt6-base-dev qtwayland5 \
    libmpv2 \
    adwaita-icon-theme xcursor-themes dmz-cursor-theme \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p "$NVM_DIR" && \
    curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh" | bash && \
    . "$NVM_DIR/nvm.sh" && nvm install 23 && \
    . "$NVM_DIR/nvm.sh" && nvm alias default 23 && \
    ln -sf "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/node" /usr/bin/node && \
    ln -sf "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/npm" /usr/bin/npm && \
    ln -sf "$NVM_DIR/versions/node/$(. $NVM_DIR/nvm.sh && nvm version)/bin/npx" /usr/bin/npx

RUN rm -rf "$PYENV_ROOT" && \
    git clone "https://github.com/pyenv/pyenv.git" "$PYENV_ROOT" && \
    LATEST_PYTHON_314=$("$PYENV_ROOT/bin/pyenv" install --list | \
        sed "s/^[[:space:]]*//" | \
        grep "^3\.14\." | \
        sort -V | \
        tail -n 1) && \
    echo "Installing Python $LATEST_PYTHON_314" && \
    "$PYENV_ROOT/bin/pyenv" install "$LATEST_PYTHON_314" && \
    "$PYENV_ROOT/bin/pyenv" global "$LATEST_PYTHON_314" && \
    python -m venv "$VIRTUAL_ENV" && \
    python -m pip install --upgrade pip

COPY requirements.txt /tmp/requirements.txt
RUN python -m pip install -r /tmp/requirements.txt && rm -rf /tmp/requirements.txt

WORKDIR /desktop_app

RUN useradd -m -d /desktop_app -s /bin/bash desktop-app && \
    chown -R desktop-app:desktop-app /desktop_app && \
    chmod -R 755 /desktop_app && \
    chmod -R a+rX /opt/pyenv /opt/nvm

USER desktop-app
