# Generated by Django 5.1.1 on 2024-09-23 14:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modification_type', models.CharField(blank=True, choices=[('insert', 'insert'), ('update', 'update'), ('delete', 'delete')], max_length=6, null=True)),
                ('user_id', models.IntegerField()),
                ('login', models.CharField(max_length=6, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modification_type', models.CharField(blank=True, choices=[('insert', 'insert'), ('update', 'update'), ('delete', 'delete')], max_length=6, null=True)),
                ('employee_id', models.IntegerField(verbose_name='Employee ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, verbose_name='PESEL')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('identity_document', models.CharField(choices=[('passport', 'Passport'), ('id_card', 'Identity Card')], max_length=8, verbose_name='Identity Document Type')),
                ('identity_document_number', models.CharField(max_length=15, verbose_name='Identity Document Number')),
                ('phone_country_code', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Country code must start with "+" followed by 2 digits.', regex='^\\+[0-9]{2}$')], verbose_name='Phone Country Code')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must contain only digits.', regex='^\\d+$')], verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')], verbose_name='Email Address')),
                ('street', models.CharField(blank=True, max_length=50, null=True, verbose_name='Street')),
                ('house_number', models.CharField(max_length=5, verbose_name='House Number')),
                ('apartment_number', models.CharField(blank=True, max_length=5, null=True, verbose_name='Apartment Number')),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Postal code must be in the format xx-xxx.', regex='^\\d{2}-\\d{3}$')], verbose_name='Postal Code')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('bank_country_code', models.CharField(max_length=2, verbose_name='Bank Country Code')),
                ('bank_account_number', models.CharField(max_length=26, validators=[django.core.validators.RegexValidator(message='Bank account number must be exactly 26 digits.', regex='^\\d{26}$')], verbose_name='Bank Account Number')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('bank_swift', models.CharField(max_length=11, verbose_name='Bank SWIFT Code')),
                ('date_of_employment', models.DateField(verbose_name='Date of Employment')),
                ('position', models.CharField(max_length=100, verbose_name='Position')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salary')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.employee'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modification_type', models.CharField(blank=True, choices=[('insert', 'insert'), ('update', 'update'), ('delete', 'delete')], max_length=6, null=True)),
                ('item_id', models.IntegerField(verbose_name='Item ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('index', models.CharField(max_length=50, verbose_name='Index')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Price must be greater than zero.')], verbose_name='Price')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Cost must be greater than zero.')], verbose_name='Cost Price')),
                ('sku', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='SKU must contain only alphanumeric characters, underscores, or hyphens.', regex='^[A-Za-z0-9_-]+$')], verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Barcode must be between 8 and 13 digits.', regex='^\\d{8,13}$')], verbose_name='Barcode')),
                ('ean', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='EAN must be exactly 13 digits.', regex='^\\d{13}$')], verbose_name='EAN')),
                ('upc', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='UPC must be exactly 12 digits.', regex='^\\d{12}$')], verbose_name='UPC')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Weight must be greater than zero.')], verbose_name='Weight (kg)')),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Dimensions must be in the format LxWxH.', regex='^\\d+(\\.\\d+)?x\\d+(\\.\\d+)?x\\d+(\\.\\d+)?$')], verbose_name='Dimensions (LxWxH)')),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Volume must be greater than zero.')], verbose_name='Volume (m³)')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Stock Quantity cannot be negative.')], verbose_name='Stock Quantity')),
                ('reorder_level', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0, message='Reorder Level cannot be negative.')], verbose_name='Reorder Level')),
                ('warehouse_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Warehouse Location')),
                ('supplier_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier SKU')),
                ('lead_time', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Lead Time must be non-negative.')], verbose_name='Lead Time (days)')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=23.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='VAT Rate cannot be negative.')], verbose_name='VAT Rate (%)')),
                ('tax_category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax Category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('modification_type', models.CharField(blank=True, choices=[('insert', 'insert'), ('update', 'update'), ('delete', 'delete')], max_length=6, null=True)),
                ('page_id', models.IntegerField(verbose_name='Page ID')),
                ('type', models.CharField(choices=[('index', 'index'), ('login', 'login')], max_length=8, verbose_name='Page Type')),
                ('name', models.CharField(max_length=50, verbose_name='Page Name')),
                ('title', models.CharField(max_length=50, verbose_name='Page Title')),
                ('template', models.CharField(help_text='HTML file name for rendering the page', max_length=50, verbose_name='Template Name')),
                ('in_menu', models.BooleanField(default=True, verbose_name='Page visible in Menu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
