# Generated by Django 5.1.1 on 2024-10-06 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pages', to='meta.category'),
        ),
        migrations.AddField(
            model_name='page',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='page',
            name='modified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefields',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefields',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.field'),
        ),
        migrations.AddField(
            model_name='pagefields',
            name='modified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagefields',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='fields',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='pages', through='core.PageFields', to='core.field'),
        ),
        migrations.AddField(
            model_name='pageimages',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageimages',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.image'),
        ),
        migrations.AddField(
            model_name='pageimages',
            name='modified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageimages',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.page'),
        ),
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='pages', through='core.PageImages', to='core.image'),
        ),
        migrations.AddField(
            model_name='text',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='text',
            name='modified_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldtexts',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.text'),
        ),
        migrations.AddField(
            model_name='field',
            name='texts',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, related_name='fields', through='core.FieldTexts', to='core.text'),
        ),
        migrations.AlterUniqueTogether(
            name='pagefields',
            unique_together={('page', 'field')},
        ),
        migrations.AlterUniqueTogether(
            name='pageimages',
            unique_together={('page', 'image')},
        ),
        migrations.AlterUniqueTogether(
            name='fieldtexts',
            unique_together={('field', 'text')},
        ),
    ]
