from .user_admin import UserAdmin
from .module_admin import ModuleAdmin
from .page_admin import PageAdmin
from .label_admin import LabelAdmin
from .translation_admin import TranslationAdmin
from .page_labels_admin import PageLabelsAdmin
from .label_translations_admin import LabelTranslationsAdmin
from .image_admin import ImageAdmin
from .page_images_admin import PageImagesAdmin
