INSERT INTO view_controllers (view_id, controller_id, is_active, created_at, created_by)
VALUES
(1, 36, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(2, 31, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(3, 24, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(4, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(5, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(5, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(5, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(6, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(6, 2, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(6, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(7, 11, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(8, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(8, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(8, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(8, 11, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(9, 6, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(9, 8, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(9, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(10, 6, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(10, 8, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(10, 10, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(11, 10, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(12, 7, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(12, 12, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(12, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 7, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 10, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 14, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 25, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(13, 34, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(15, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(15, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 13, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 18, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 39, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(17, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(17, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(17, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(17, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(17, 23, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 18, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 24, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(19, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 25, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 23, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 24, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(22, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 20, TRUE, CURRENT_TIMESTAMP, :superuser_id);
