INSERT INTO view_controllers (view_id, controller_id, is_active, created_at, created_by)
VALUES
(1, 36, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(2, 31, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(3, 35, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(4, 38, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(5, 36, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(6, 40, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(7, 32, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(8, 37, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(8, 39, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(9, 24, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(10, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(11, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(11, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(11, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(12, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(12, 2, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(12, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(13, 11, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(14, 11, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(15, 6, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(15, 8, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(15, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 6, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 8, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(16, 10, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(17, 10, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 7, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 12, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(18, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 7, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 10, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 14, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 25, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(19, 34, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(20, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(21, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(21, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(22, 13, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(22, 18, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(22, 19, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(22, 39, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(23, 23, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 18, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(24, 24, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(25, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(25, 25, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(26, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(26, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(26, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(26, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(26, 23, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 4, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 5, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 9, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 15, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 16, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 22, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(27, 24, TRUE, CURRENT_TIMESTAMP, :superuser_id),

(28, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(29, 17, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(29, 20, TRUE, CURRENT_TIMESTAMP, :superuser_id);
