INSERT INTO customers (
    first_name,
    last_name,
    company_name,
    payment_term,
    tax_id,
    email,
    phone_number,
    street,
    house_number,
    apartment_number,
    postal_code,
    city,
    country,
    shipping_street,
    shipping_house_number,
    shipping_apartment_number,
    shipping_postal_code,
    shipping_city,
    shipping_country,
    user_id,
    is_active,
    created_at,
    created_by
)
SELECT
    CASE WHEN i % 2 = 0 THEN 'Anna' ELSE 'Jan' END AS first_name,
    CASE WHEN i % 2 = 0 THEN 'Nowak' ELSE 'Kowalski' END AS last_name,
    'Firma ' || lpad(i::text, 3, '0') AS company_name,
    14 + (i % 30) AS payment_term,
    lpad((1000000000 + i)::text, 10, '0') AS tax_id,
    'firma' || lpad(i::text, 3, '0') || '@example.pl' AS email,
    '+48' || (500000000 + i)::text AS phone_number,
    'Ulica ' || ((i % 20) + 1)::text AS street,
    ((i % 50) + 1)::text AS house_number,
    CASE WHEN i % 5 = 0 THEN ((i % 20) + 1)::text ELSE NULL END AS apartment_number,
    lpad(((i % 90) + 10)::text, 2, '0') || '-' || lpad(((i % 900) + 100)::text, 3, '0') AS postal_code,
    CASE WHEN i % 3 = 0 THEN 'Krakow' WHEN i % 3 = 1 THEN 'Warszawa' ELSE 'Wroclaw' END AS city,
    'Polska' AS country,
    NULL AS shipping_street,
    NULL AS shipping_house_number,
    NULL AS shipping_apartment_number,
    NULL AS shipping_postal_code,
    NULL AS shipping_city,
    NULL AS shipping_country,
    i + 1 AS user_id,
    TRUE,
    CURRENT_TIMESTAMP,
    :superuser_id
FROM generate_series(1, 40) AS s(i);
