INSERT INTO exchange_rates (rate, valid_from, valid_to, base_currency_id, quote_currency_id, is_active, created_at, created_by)
VALUES
(4.3000, CURRENT_DATE + INTERVAL '1 days', CURRENT_DATE + INTERVAL '30 days', 2, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(3.9500, CURRENT_DATE + INTERVAL '1 days', CURRENT_DATE + INTERVAL '30 days', 3, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(0.2326, CURRENT_DATE + INTERVAL '1 days', CURRENT_DATE + INTERVAL '30 days', 1, 2, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(0.2532, CURRENT_DATE + INTERVAL '1 days', CURRENT_DATE + INTERVAL '30 days', 1, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(1.0890, CURRENT_DATE + INTERVAL '1 days', CURRENT_DATE + INTERVAL '30 days', 2, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(0.9180, CURRENT_DATE + INTERVAL '1 days', CURRENT_DATE + INTERVAL '30 days', 3, 2, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(4.2800, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE, 2, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(3.9200, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE, 3, 1, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(0.2336, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE, 1, 2, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(0.2551, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE, 1, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(1.0918, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE, 2, 3, TRUE, CURRENT_TIMESTAMP, :superuser_id),
(0.9159, CURRENT_DATE - INTERVAL '30 days', CURRENT_DATE, 3, 2, TRUE, CURRENT_TIMESTAMP, :superuser_id);
