INSERT INTO items (
    index,
    name,
    description,
    ean,
    purchase_price,
    vat_rate,
    margin,
    lead_time,
    is_available,
    is_fragile,
    is_package,
    is_returnable,
    expiration_date,
    width,
    height,
    length,
    weight,
    stock_quantity,
    min_stock_level,
    max_stock_level,
    moq,
    category_id,
    unit_id,
    supplier_id,
    is_active,
    created_at,
    created_by
)
SELECT
    'ITM-' || lpad(i::text, 4, '0') AS index,
    'Produkt ' || lpad(i::text, 4, '0') AS name,
    'Opis produktu ' || lpad(i::text, 4, '0') AS description,
    lpad((5900000000000 + i)::text, 13, '0') AS ean,
    ROUND((5 + (i % 20) * 3 + (i / 10)::int)::numeric, 2) AS purchase_price,
    CASE
        WHEN i % 10 = 0 THEN 0.08
        WHEN i % 6 = 0 THEN 0.05
        ELSE 0.23
    END AS vat_rate,
    ROUND((0.15 + (i % 10) * 0.01)::numeric, 3) AS margin,
    (3 + (i % 30)) AS lead_time,
    TRUE AS is_available,
    (i % 7 = 0) AS is_fragile,
    (i % 5 = 0) AS is_package,
    (i % 9 = 0) AS is_returnable,
    CASE WHEN i % 12 = 0 THEN CURRENT_DATE + INTERVAL '365 days' ELSE NULL END AS expiration_date,
    ROUND((0.10 + (i % 10) * 0.05)::numeric, 3) AS width,
    ROUND((0.10 + (i % 8) * 0.04)::numeric, 3) AS height,
    ROUND((0.15 + (i % 12) * 0.05)::numeric, 3) AS length,
    ROUND((0.20 + (i % 15) * 0.10)::numeric, 3) AS weight,
    (5000 + (i % 5000)) AS stock_quantity,
    (2000 + (i % 500)) AS min_stock_level,
    (12000 + (i % 3000)) AS max_stock_level,
    (5 + (i % 10)) AS moq,
    ((i - 1) % 12) + 1 AS category_id,
    ((i - 1) % 3) + 1 AS unit_id,
    ((i - 1) % 3) + 1 AS supplier_id,
    TRUE,
    CURRENT_TIMESTAMP,
    :superuser_id
FROM generate_series(1, 60) AS s(i);
